# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd ClientApp
    echo $PATH
  displayName: Move to Client App
- script: |
    npm install -g @angular/cli
    echo $PATH
  displayName: 'Install Angular'
- script: 
    npm install
    echo $PATH
  displayName: 'Install'
- script: 
    ng build --prod
    echo $PATH
  displayName: 'Build'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'ClientApp/build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
